### ISSUE TITLE
is sdk support swift 3 ?

### ISSUE THREAD

**Issue by MahipalV12** [AppLozic/Applozic-iOS-Chat-Samples#16]

**Comment by mukeshthawani** [comment]
Yes, it supports Swift-3.

**Comment by MahipalV12** [comment]
but its show only swift 2.3 version and in that only 2-3 UI controllers are in swift 2.3

**Comment by mukeshthawani** [comment]
Try this sample app: https://github.com/AppLozic/Applozic-iOS-Chat-Samples/tree/master/sampleapp-swift
