### ISSUE TITLE
Push Notification are not working on new messages

### ISSUE THREAD

**Issue by MahipalV12** [AppLozic/Applozic-iOS-Chat-Samples#17]
sample app: https://github.com/AppLozic/Applozic-iOS-Chat-Samples/tree/master/sampleapp-swift

Application environment :- Adhoc in Release mode
Note:-  device token from sampleCode and PEM file uploaded at /dashboard.applozic.com are tested and working fine . 

Sno | Device Key | Registration Id | Status | Created Time | Device Type
-- | -- | -- | -- | -- | --
1 | 8xx7-cx18-4xx4-ad5a-8ss0 | 8xxxxxfc48a | KeyStore Not Found | 2017-09-18 11:03:39.288 | IOS

**Comment by mukeshthawani** [comment]
You can test it here: https://www.applozic.com/docs/push-notification-test.html

**Comment by mukeshthawani** [comment]
Add password of the certificate on Applozic dashboard.

**Comment by MahipalV12** [comment]
yes, i already test on push-notification-test.html  not working (result attached in above comment) 

Add password of the certificate on Applozic dashboard. --> Already added

**Comment by MahipalV12** [comment]
wait a while i'm sharing screen shot.

**Comment by MahipalV12** [comment]
Sorry @mukeshthawani , 
now i added passcode and its working but some other issue are arising.

code is clone and pod updated (version 4.2.0). we have three different folder
-> [Applozic-iOS-Chat-Samples](https://github.com/AppLozic/Applozic-iOS-Chat-Samples/tree/master/ApplozicCocoaPodDemo) ->(Notification are working fine)
->[ sampleapp->swift](https://github.com/AppLozic/Applozic-iOS-Chat-Samples/tree/master/sampleapp-swift) (Notification are not working)
-> [sampleapp](https://github.com/AppLozic/Applozic-iOS-Chat-Samples/tree/master/sampleapp) -> showing "PASSWORD REQUIRED" alert after login

**Comment by mukeshthawani** [comment]
Just try one sample app and share what is not working.

**Comment by MahipalV12** [comment]
ok, i'm working with  [Applozic-iOS-Chat-Samples ](https://github.com/AppLozic/Applozic-iOS-Chat-Samples/tree/master/ApplozicCocoaPodDemo) 
-->   notifications are missing when i text randomly to participant.
-->   read status are not showing proper one device is in foreground and another is in background. (
![screen shot 2017-09-18 at 7 37 08 pm](https://user-images.githubusercontent.com/28589483/30546406-30221a7c-9caa-11e7-839d-6d793f98ff5f.png)
Screen attached).

**Comment by mukeshthawani** [comment]
When the app is closed/killed on the other side then read receipt will not update.

Share the logs at support@applozic.com for missing notifications.

**Comment by MahipalV12** [comment]
"Share the logs at support@applozic.com for missing notifications." which type of log.  i had sent messages to participant(app state : terminate ) and participant received only some of push notification most of are not delivered to device.

read status are not showing proper when one device is in foreground and another is in background.
here is Screen Shot
![img_3661](https://user-images.githubusercontent.com/28589483/30576457-a1ef5cca-9d25-11e7-8794-98a77e49d798.PNG)

**Comment by mukeshthawani** [comment]
All the logs which you see on your Xcode console.

**Comment by MahipalV12** [comment]
okay, log file of sender user sent on support@applozic.com pls check.

**Comment by MahipalV12** [comment]
and pls check the read status (screen shot already shared above): its not working properly

**Comment by mukeshthawani** [comment]
We have not received any email.

**Comment by MahipalV12** [comment]
its already sent from side. Pls share me any otherEmail id

**Comment by mukeshthawani** [comment]
From which id you have sent? Also, just send it again.

**Comment by MahipalV12** [comment]
that one is my official Id (mahipal.singh@..).. Resend sent pls check

**Comment by mukeshthawani** [comment]
Just received.

**Comment by MahipalV12** [comment]
ok

**Comment by MahipalV12** [comment]
@mukeshthawani, sure we can go through teamviewer.
i'll mail you my teamviewer id

**Comment by MahipalV12** [comment]
id mailed pls check and let me know when you are ready.

**Comment by MahipalV12** [comment]
did you update anything at server side? it seems like notification are receiving but not in sequeue. yesterday, its just opposite, sequence of notification are in right order but last 2 notifications are missed.

**Comment by mukeshthawani** [comment]
No, we have not changed anything. The sequence may change sometimes.

I will close this as push notifications are working. If you have any other issue, you can share the details at support@applozic.com

**Comment by MahipalV12** [comment]
Thanks @mukesh
